version: '3.8'

services:
  gateway_service:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    command: dotnet GatewayService.dll
    volumes:
      - ./GatewayService:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  responsible_service:
    build:
      context: .
      dockerfile: ResponsibleService/Dockerfile
    command: dotnet ResponsibleService.dll
    volumes:
      - ./ResponsibleService:/app
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
