version: '3.8'

services:
  gateway_service:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    image: rabotarabocaa001/hse-sa-microservices-api-gateway:${{ github.sha }}  # Добавляем тег
    command: dotnet GatewayService.dll
    depends_on:
      - responsible_service
      - user_service
    volumes:
      - ./GatewayService:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  responsible_service:
    build:
      context: .
      dockerfile: ResponsibleService/Dockerfile
    image: rabotarabocaa001/hse-sa-microservices-api-responsible:${{ github.sha }}  # Добавляем тег
    command: dotnet ResponsibleService.dll
    volumes:
      - ./ResponsibleService:/app
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  user_service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    image: rabotarabocaa001/hse-sa-microservices-api-user:${{ github.sha }}  # Добавляем тег
    command: dotnet UserService.dll
    volumes:
      - ./UserService:/app
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
