name: CI and CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ["6.0"]  # Используйте актуальную версию .NET

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Замените на нужную версию .NET
        
    - name: Restore dependencies
      run: |
        dotnet restore user_service.csproj
        dotnet restore responsible_service.csproj
        dotnet restore gateway_service.csproj

    - name: Build the projects
      run: |
        dotnet build user_service.csproj --configuration Release
        dotnet build responsible_service.csproj --configuration Release
        dotnet build gateway_service.csproj --configuration Release
        
    - name: Run tests
      run: |
        dotnet test user_service.csproj
        dotnet test responsible_service.csproj
        dotnet test gateway_service.csproj

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:user_service ./user_service
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:responsible_service ./responsible_service
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:gateway_service ./gateway_service

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_REPOSITORY }}:user_service
        docker push ${{ secrets.DOCKER_REPOSITORY }}:responsible_service
        docker push ${{ secrets.DOCKER_REPOSITORY }}:gateway_service
