name: Docker Push

on:
  push:
    branches:
      - master  # или ваша ветка
  workflow_dispatch:  # добавляем поддержку ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build Docker images with Docker Compose
        run: |
          docker-compose build

      - name: Tag images with commit hash and push to Docker Hub
        run: |
          # Тегируем образы с хешем коммита
          docker tag gateway_service rabotarabocaa001/hse-sa-microservices-api-gateway:${{ github.sha }}
          docker tag responsible_service rabotarabocaa001/hse-sa-microservices-api-responsible:${{ github.sha }}
          docker tag user_service rabotarabocaa001/hse-sa-microservices-api-user:${{ github.sha }}

          # Отправляем образы в Docker Hub
          docker push rabotarabocaa001/hse-sa-microservices-api-gateway:${{ github.sha }}
          docker push rabotarabocaa001/hse-sa-microservices-api-responsible:${{ github.sha }}
          docker push rabotarabocaa001/hse-sa-microservices-api-user:${{ github.sha }}
