name: CI and CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ["6.0"]  # Используйте актуальную версию .NET

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Замените на нужную версию .NET
        
    - name: Restore dependencies
      run: |
        dotnet restore ./UserService/UserService.csproj
        dotnet restore ./ResponsibleService/ResponsibleService.csproj
        dotnet restore ./GatewayService/GatewayService.csproj

    - name: Build the projects
      run: |
        dotnet build ./UserService/UserService.csproj --configuration Release
        dotnet build ./ResponsibleService/ResponsibleService.csproj --configuration Release
        dotnet build ./GatewayService/GatewayService.csproj --configuration Release
        
    - name: Run tests
      run: |
        dotnet test ./UserService/UserService.csproj
        dotnet test ./ResponsibleService/ResponsibleService.csproj
        dotnet test ./GatewayService/GatewayService.csproj

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:user_service ./UserService
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:responsible_service ./ResponsibleService
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:gateway_service ./GatewayService

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_REPOSITORY }}:user_service
        docker push ${{ secrets.DOCKER_REPOSITORY }}:responsible_service
        docker push ${{ secrets.DOCKER_REPOSITORY }}:gateway_service
